name: substring_highlight
description: Highlight Flutter text at the character-level for customizable and simple search term highlighting.
version: 1.0.25        #NOEDIT
homepage: https://github.com/remoteportal/substring_highlight

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
